language: node_js
node_js:
  - 12
script:
  - echo "skipping tests"
deploy:
  provider: heroku
  app: threadly-manjiltamang
  on:
    branch: master
  api_key:
    secure: IdCmjjHtIc2HexZihgWKIwLvoRV8E9Oh6BI/0Yk1qDZfX2p/Cnbh/7eVjMMLI3+fo0/fAEnfqe9PXRV5ifntWCfHbCb12YO+XegBXXSa747Jg1tEB0EBJogsYzaoOSHYQAOSeTsuBLsVKNqdNTler8cnKWc6hQ8AHDRxm8B+7wM2bJkJkFTP6DB1wRrN8dDH+X4EGDN1FqJYfQKlRJNNDwy9A4oNvWBkC3+IhRiuhZb/kbtMNhMperBFz6V4gC7R09bd4akbfqTB8yBIHc4quAIkUS7UFmu5kNlj2fchr+ki0qbnte7KuuyBUEoWZOIFc4aEOwAHy556+PNR4BhPQh49E8tLn8IVka4wnPUTkmwwPRVGWM2tObMcP2K8mw2EKZDjeq7wgzDAEP7+R1RQou/3xl3JJzNe/8b5zd9Y+g+f995axqRgdUhXQDNN6dgaYD7sMMs0CmnSqZq4SoJIOVFAXGp97P1mQmN3hEXQkUZ2kiPl0od4KiC6c0lHhZ9hsihu+qh5AGSK7Rnw5qdAh6W7wKoQdCsoJX4xscptwGIne9tmZoV6RH8K4MuXy2Z3erarngFEJSKNIJER37B299glblFrwZmAeeS390PaBrdvIltkkcdtg07s84FOglEPIYSNQtfllx1V3MvK5y1YiCBZW4F29rTbUIxyj42HU4M=
