language: node_js
node_js:
  - 12
script:
  - echo "skipping tests"
deploy:
  skip_cleanup: true
  provider: heroku
  app: threadly-manjiltamang
  on:
    branch: master
  api_key:
    secure: AAb4/gDmg3IymU9ekObHpKnkFRP6Bz40AZI5vxY0THxn2hdhz1xn7iodqPZgytUJ6sxlOBwqEi515Orb3G2mY8zcCSzUaIjYDxtuhWaVtIol6BkxdN5ZnRvw42ZFJJaoTFPeWfTHZjdXZrpYwmnpYEeJ+w3hvMFSwACLNNUCOyDEVnIbPQ63Ozax1TH3f+UUGHO3DOd3i3fg37xM+FDXUsm7QEZ/ogQoEeFx0Tdidyxul8MXx7DsBfM9sImx1mmfa9GAAsLHPGaQZYuizibPRTqzfVFnxUftg2jHVTRkFR15QKTyiDtOggtCnOXmaoAw8uz/f4otyEdThDiEPuPQVXc5CUtvNNa0xv+uHIRc2zKHuOMqnK2N8pn/EFy7M0xWqkM3azbqsiZYcPMfauKY+/Ff+Khpjb5SaMGzMsXx0quIYpoimf+PCVNmG9DB3jzHWg/Z87ckZ2ahfL4dntKzVHAC9Y0pMi/xnlIG8oE7qvv/ZNqwpqbfOzvbnfKac3I6BBELcmfEU22Lza+McHiQJ4n3gGBUcrvLB0rLPtRok+MCjMjsH+cg438OhVza7jJSzASx8Jkf4AxAw0ziqWCRBfQqrSZ5Nc8Y8L7F0xsc2g9hnlHQB29vispDnTQALNBYWxDRsBlWYZHjeHukNI+yIgL+K28SjhRm3GVwO2WxGiw=
