language: node_js
node_js:
- 12
script:
- echo "skipping tests"
deploy:
  provider: heroku
  app: threadly-manjiltamang
  on:
    branch: master
  api_key:
    secure: fl6o3Bdhbx6PCsZgZ5fG2XmqevA1NaTBU2Ej2/YUG0tk6yQigzjBT17aaMtZ4zs2gkR38wgpeR0HRnBjLZHQDzol5mmgPqaT9GdV1W6AftP7ugva8DjX9X56+EIu94xweO9//6BUyzpFSRVz/YjhrSAZuItd6aZdT1FHlemlQlXvad3ZDlj9kQF3AiVDQN3IF9pWpZJHhTonSyRV7ZJOr8nebbxN7a4iv7XAksmHfz5JEyqjtnCButq7x40dbNU3eKoNoQqbrvszxt9qyGAHQK3QT4XmghPx/+5aqZDHh5exKzHZkYgE5YC0X75ArfmEBR1+pLUE5PAYJTC0FUOJhQ2gfJG4cAa/7NH68MHcBquRMNeA/JgeH+D+69Z0vbblkKcFU2SIn5SUeAcApMQ0/UoRC8bhFIaiJ46bD88djj59xbnpvrey1yB+ump/LqFK6rjHDptg4wOn02Fr1tJAeJtR17UoipHbQQYrt9fZPPU8IRh//ye3eXdKaLZsRO/OH86pGqpXaFiXaMNA2scdA1F/FrWmUY+WjJZpzl0VR3IoKNNcNP5pv1UPSgbOJOjiDREbeHwo5wm5Qeqa6vZymkQ2kvZ3oyYngjxvdWoPvukBwXzy8yIgrGkyB5b3MZu/XMQKT8D2WdjYWmSErjCbhJPoT17DaH+8XWfNsDTooGo=
