language: node_js
node_js:
  - 12
script:
  - echo "skipping tests"
deploy:
  provider: heroku
  app: threadly-manjiltamang
  on:
    branch: master
  api_key:
    secure: H4TJYdoCHJahSW7WLA0UDPJRkzokXKZAXodUu/jU7PunrVmyT8Sndfho4Ri50D5GxpFvrvmcUywkT2TXguTz9qmZ2PN4YEUgyi1FUtxJKvZ9+qrLbDZQzrQIYBnzNFCjiSPP1QeeeOu6Nd4f9N9QSSM87X0DipwKx55N5igSt+MuZYrWyX2vLe53vosp5t66TvLhbBOYS8rknUxO8Jsgv7qXgIvHRUHcYjLQOvxeU9VD1IEfyxT77M+Ay1KzvsCl85pd9j9QGTP7V1bCq4RleR56ExN9p8WYMQ7xmAa+074VItCvMWwp2mqPKk4K6yzbUkldd9oKM/WXVKxwpTBo8A+M3ITGdlepwd8BobOilhejHj2SgKPXP87fkT6B74dhQlyWEPhxJiqL3BPQJDaxyPpmx2J2lK/hSJ7OzV3pZaoHAKphRH4otIrYIfRFtVXFGQs5b2vO72zScfuoeYqsVHzCrfu8hh1dm9opUepiKiLLaTKXQ5l/+XVaAD4drGSXsn2IvwoYbjg/4I44o8FsmAHTGTzwqBsOlg8vcxd5FWZ7YJ5A4Z+LsOhrI8cNM6DURwLVjJh36IwVgv0rVDkIFGcQN0vE2UIWYSWl9z0+/2StYlyqUYigyWmqiJOUOs220t7un+28wGFbB784KkP8VAWBiBrPDaIJ+GBVY49t80Y=
